// Query keys for TanStack Query
export const qk = {
  auth: () => ["auth"] as const,
  workflows: () => ["workflows"] as const,
  workflow: (id: string) => [...qk.workflows(), id] as const,
  publicWorkflows: () => ["workflows", "public"] as const,
  executions: () => ["executions"] as const,
  execution: (id: string) => [...qk.executions(), id] as const,
  lastExecution: (workflowId: string) => ["executions", "last", workflowId] as const,
  sharedWorkflow: (id: string) => ["workflows", "shared", id] as const,
  providers: () => ["providers"] as const,
  aiQuota: () => ["ai", "quota"] as const,
  secrets: () => ["secrets"] as const,
  apiKeys: () => ["apiKeys"] as const,
  chats: () => ["chats"] as const,
  chat: (id: string) => ["chats", id] as const,
  admin: () => ["admin"] as const,
  adminOverview: () => [...qk.admin(), "overview"] as const,
  adminSettings: () => [...qk.admin(), "settings"] as const,
  adminQueue: () => [...qk.admin(), "queue"] as const,
  adminUsers: () => [...qk.admin(), "users"] as const,
  adminExecutions: (filters: string) => [...qk.admin(), "executions", filters] as const,
  adminWorkflows: () => [...qk.admin(), "workflows"] as const,
  adminAnalytics: (days: number) => [...qk.admin(), "analytics", days] as const,
  adminModels: () => [...qk.admin(), "models"] as const,
}